# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=2)),
                ('event', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Contest Start time')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Contest End time')),
                ('event_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Platform'),
        ),
    ]
