# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
